# Server Port (Render tu dong cap cong qua bien $PORT)
server.port=${PORT:8080}

# Application Name
spring.application.name=cinema-backend

# ===============================
# PostgreSQL Configuration (Doc tu Cloud, neu khong co thi dung localhost)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Hibernate ddl-auto: Tu dong tao bang len Neon Cloud
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET:local_dev_key_khong_so_lo_123456789012345678901234567890}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# Redis Configuration (Ho tro ket noi Upstash Redis)
# ===============================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}
